// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_UYOs1ldsaFh107AdRiZFcL06I2vcFD4',
    appId: '1:972309590484:web:2a4a66c8813083c91c2641',
    messagingSenderId: '972309590484',
    projectId: 'my-trip-nick',
    authDomain: 'my-trip-nick.firebaseapp.com',
    storageBucket: 'my-trip-nick.firebasestorage.app',
    measurementId: 'G-JCCTPG6PDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2gaozd1njPZxt1h1gd4sXSdcpQRDmsE',
    appId: '1:972309590484:android:ac7a703c48713a241c2641',
    messagingSenderId: '972309590484',
    projectId: 'my-trip-nick',
    storageBucket: 'my-trip-nick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFlmlqKT1sk76VwFIlND_J8PipPSBwWBY',
    appId: '1:972309590484:ios:9ca587892c2991a01c2641',
    messagingSenderId: '972309590484',
    projectId: 'my-trip-nick',
    storageBucket: 'my-trip-nick.firebasestorage.app',
    androidClientId: '972309590484-3qogiggmhg8irg95arm62upuve3htlkq.apps.googleusercontent.com',
    iosClientId: '972309590484-ibo0gqo48suvtgrpg252u3p5e5tguv8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSrc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFlmlqKT1sk76VwFIlND_J8PipPSBwWBY',
    appId: '1:972309590484:ios:9ca587892c2991a01c2641',
    messagingSenderId: '972309590484',
    projectId: 'my-trip-nick',
    storageBucket: 'my-trip-nick.firebasestorage.app',
    androidClientId: '972309590484-3qogiggmhg8irg95arm62upuve3htlkq.apps.googleusercontent.com',
    iosClientId: '972309590484-ibo0gqo48suvtgrpg252u3p5e5tguv8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSrc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_UYOs1ldsaFh107AdRiZFcL06I2vcFD4',
    appId: '1:972309590484:web:3c1e3443b37136bb1c2641',
    messagingSenderId: '972309590484',
    projectId: 'my-trip-nick',
    authDomain: 'my-trip-nick.firebaseapp.com',
    storageBucket: 'my-trip-nick.firebasestorage.app',
    measurementId: 'G-04VYLDFRBM',
  );
}
